apiVersion: v1
kind: Service
metadata:
  name: spring-music
spec:
  selector:
    app.kubernetes.io/name: spring-music
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
